{
    'name': "School Management",
    'summary': "School Management Module",
    'description': """ This School Management Module is useful for Maintained the Student,Classes,School Transport and Hostel and More features of School""",
    'author': 'Alan Technologies',
    'company': 'Alan Technologies',
    'maintainer': 'Alan Technologies',
    'website': "https://alantechnologies.in/",
    "license": "AGPL-3",
    'category': 'Education',
    'version': '18.0.1.0.0',
    'depends': ['base', 'contacts', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'report/ir_actions_report.xml',
        'report/ir_actions_report_card.xml',
        'report/fee_receipt.xml',
        'views/menuitems.xml',
        'views/sequences.xml',
        'views/student.xml',
        'views/parent.xml',
        'views/student_document.xml',
        'views/classes.xml',
        'views/subject.xml',
        'views/teacher.xml',
        'views/exam.xml',
        'views/exam_result.xml',
        'views/transport.xml',
        'views/fee.xml',
        'views/hostel.xml',
        'views/fee_type.xml',
        'views/academic_year.xml',
        'views/student_attendance.xml',
        'views/dashboard_action.xml',
        'wizard/fee_payment.xml',
        'wizard/report_card.xml',
    ],
    'demo': [
    ],
    'assets': {
    'web.assets_backend': [
        'at_school_management/static/src/js/dashboard.js',
        'at_school_management/static/src/xml/dashboard.xml',
        'at_school_management/static/src/scss/dashboard.scss',
    ],
    },
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
